export const HIT_SCHEMA = {
  AUTOCOMPLETE: {
    cuisine: {
      _modifier: "getFirstArrayElement",
      breadcrumbs: "cuisine",
    },
    highlighted: {
      city: "_highlightResult.locality.value",
      cuisine: {
        _modifier: [
          {
            name: "getFirstArrayElement",
          },
          {
            name: "get",
            key: "value",
          },
        ],
        breadcrumbs: "_highlightResult.cuisine",
      },
      neighborhood: "_highlightResult.neighborhood.value",
      state: "region",
    },
    id: "id.resy",
    image: {
      _modifier: "getFirstArrayElement",
      breadcrumbs: "images",
    },
    isGda: "is_global_dining_access",
    location: {
      city: "locality",
      code: "location.code",
      name: "location.name",
      neighborhood: "neighborhood",
      state: "region",
    },
    name: "name",
    urlSlug: "url_slug",
    _geoloc: "_geoloc",
  },
  SEARCH_RESULT: {
    activeNotifications: {
      _modifier: [
        {
          name: "arrayToDictionary",
          key: "service_type_id",
        },
      ],
      breadcrumbs: "availability.notifies",
    },
    availableServiceTypes: {
      _modifier: "dictionaryToArray",
      breadcrumbs: "availability.service_types",
    },
    collections: "collections",
    cuisine: {
      _modifier: "getFirstArrayElement",
      breadcrumbs: "cuisine",
    },
    currency: "currency_symbol",
    events: "availability.events",
    favorite: "favorite",
    id: "id.resy",
    image: {
      _modifier: "getFirstArrayElement",
      breadcrumbs: "images",
    },
    isGda: "is_global_dining_access",
    location: {
      code: "location.code",
      name: "location.name",
      neighborhood: "neighborhood",
    },
    name: "name",
    objectID: "objectID",
    priceRange: "price_range_id",
    rating: {
      _modifier: "rating",
      breadcrumbs: "rating.average",
    },
    reopen: "reopen",
    totalRatings: "rating.count",
    urlSlug: "url_slug",
    whyWeLikeIt: {
      _modifier: "getWhyWeLikeIt",
      breadcrumbs: "content",
    },
    _geoloc: "_geoloc",
  },
};
export const NOTIFY_SCHEMA = {
  day: "day",
  end: "time_preferred_end",
  seats: "num_seats",
  serviceTypeId: "service_type_id",
  start: "time_preferred_start",
  venueId: "venue_id",
};
export const VENUE_SCHEMA = {
  FINDER: {
    activeNotifications: {
      _modifier: [
        {
          name: "arrayToDictionary",
          key: "service_type_id",
        },
      ],
      breadcrumbs: "notifies",
    },
    availableServiceTypes: {
      _modifier: "dictionaryToArray",
      breadcrumbs: "venue.service_types",
    },
    averagePriceStr: "venue.ticket.average_str",
    collections: "venue.collections",
    cuisine: "venue.type",
    currencyDict: "venue.currency",
    currency: "venue.currency_symbol",
    favorite: "venue.favorite",
    gdaConciergeBooking: "venue.gda_concierge_booking",
    id: "venue.id.resy",
    images: {
      _modifier: [
        {
          name: "getFromSource",
          needsSource: true,
          key: "templates",
        },
        {
          name: "get",
          key: "images",
        },
      ],
      breadcrumbs: "venue.default_template",
    },
    isFly: {
      _modifier: "isFly",
      breadcrumbs: "venue.inventory.type.id",
    },
    isGda: "is_global_dining_access",
    location: {
      code: "venue.location.code",
      neighborhood: "venue.location.neighborhood",
      name: "venue.location.name",
    },
    name: "venue.name",
    priceRange: "venue.price_range",
    rating: "venue.rating",
    reopen: "venue.reopen",
    responsiveImages: "venue.responsive_images",
    source: "venue.source",
    totalRatings: "venue.total_ratings",
    urlSlug: "venue.url_slug",
    whyWeLikeIt: {
      _modifier: "getWhyWeLikeIt",
      breadcrumbs: "content",
    },
  },
  INVITE: {
    config: "config",
    contact: {
      phone: {
        _modifier: "formatPhone",
        breadcrumbs: "contact.phone_number",
      },
      url: "contact.url",
    },
    id: "id",
    location: {
      address1: "location.address_1",
      address2: "location.address_2",
      coords: {
        lat: "location.latitude",
        long: "location.longitude",
      },
      city: "location.locality",
      state: "location.region",
      postalCode: "location.postal_code",
    },
    name: "name",
    social: "social",
  },
  LIST_VENUES: {
    id: "id.resy",
    name: "name",
    location: {
      code: "location.id",
      neighborhood: "location.neighborhood",
      city: "location.locality",
      state: "location.region",
    },
    urlSlug: "url_slug",
  },
  VENUE: {
    announcement: "announcement",
    averagePriceStr: "ticket.average_str",
    collections: "collections",
    contact: {
      phone: {
        _modifier: "formatPhone",
        breadcrumbs: "contact.phone_number",
      },
      url: "contact.url",
    },
    content: "content",
    cuisine: "type",
    currencyDict: "currency",
    currency: "currency_symbol",
    favorite: "favorite",
    id: "id.resy",
    fb_pixel: "id.fb_pixel",
    gdaConciergeBooking: "gda_concierge_booking",
    images: "images",
    isFly: {
      _modifier: "isFly",
      breadcrumbs: "inventory.type.id",
    },
    isMobileFirstLogin: "user_login_preference.mobile_first",
    isGda: "is_global_dining_access",
    isGdaOnly: "is_global_dining_access_only",
    name: "name",
    largePartyMessage: "large_party_message",
    locale: "locale",
    location: {
      address1: "location.address_1",
      address2: "location.address_2",
      code: "location.code",
      coords: {
        lat: "location.latitude",
        long: "location.longitude",
      },
      neighborhood: "location.neighborhood",
      city: "location.locality",
      state: "location.region",
      postalCode: "location.postal_code",
      country: "location.country",
    },
    maxPartySize: "max_party_size",
    metadata: {
      description: "metadata.description",
    },
    minPartySize: "min_party_size",
    priceRange: "price_range_id",
    rater: "rater",
    reopen: "reopen",
    responsiveImages: "responsive_images",
    resySelect: "resy_select",
    safety_info_url: "safety_info_url",
    safetyInfoUrl: "safety_info_url",
    safetyCategories: "safety_categories",
    social: "social",
    taxIncluded: "tax_included",
    urlSlug: "url_slug",
    customAffiliation: "custom_affiliation",
    customAffiliations: "custom_affiliations",
    venueGroup: {
      id: "venue_group.id",
      name: "venue_group.name",
      venues: "venue_group.venues",
    },
  },
};
export const SLOT_SCHEMA = {
  CLASSIC: {
    badge: "reservation_config.badge",
    colors: "display_config.color",
    serviceTypeId: "shift.service.type.id",
    time: "date.start",
    type: "config.type",
    token: "config.id",
  },
  FLY: {
    badge: "reservation_config.badge",
    colors: "display_config.color",
    isGda: "is_global_dining_access",
    serviceTypeId: "shift.service.type.id",
    templateId: "template.id",
    time: "date.start",
    token: "config.token",
    type: "config.type",
  },
  SEARCH: {
    CLASSIC: {
      badge: "reservation_config.badge",
      colors: "display_config.color",
      time: "date.start",
      token: "config.id",
      type: "config.type",
    },
    FLY: {
      badge: "reservation_config.badge",
      colors: "display_config.color",
      isGda: "is_global_dining_access",
      time: "date.start",
      token: "config.token",
      type: "config.type",
    },
  },
};
export const RESERVATION_SCHEMA = {
  attendee: "attendee",
  bookOnBehalf: "book_on_behalf",
  cancellation: "cancellation",
  cancellationPolicy: "cancellation_policy",
  change: "change",
  content: "content",
  currencyCode: "currencyCode",
  day: "day",
  event: {
    eventTypeId: "event_type_id",
    eventUrlSlug: "event_url_slug",
    name: "name",
    packageName: "package_name",
  },
  features: "features",
  id: "reservation_id",
  isExpired: "rating.expired",
  isNow: {
    _modifier: "reservationIsNow",
    breadcrumbs: "when",
  },
  isGda: "is_global_dining_access",
  occasion: "occasion",
  pastOrFuture: {
    _modifier: "pastOrFuture",
    breadcrumbs: "when",
  },
  party: "party",
  payment: "payment",
  paymentMethod: "payment_method",
  price: "price",
  rating: "rating.value",
  seats: "num_seats",
  serviceCharge: "service_charge",
  serviceTypeId: "service_type_id",
  share: "share",
  specialRequest: "special_request",
  tableType: "config.type",
  template: "template",
  time: "time_slot",
  token: "resy_token",
  conciergeResyToken: "concierge_resy_token",
  venue: {
    id: "id",
    images: "images",
    isGda: "is_global_dining_access",
    contact: {
      phone: {
        _modifier: "formatPhone",
        breadcrumbs: "contact.phone_number",
      },
      url: "contact.url",
    },
    hideAllergyQuestion: "hide_allergy_question",
    hideOccasionQuestion: "hide_occasion_question",
    hideSpecialRequestQuestion: "hide_special_request_question",
    location: {
      address1: "location.address_1",
      address2: "location.address_2",
      city: "location.locality",
      code: "location.code",
      coords: {
        lat: "location.latitude",
        long: "location.longitude",
      },
      state: "location.region",
      postalCode: "location.postal_code",
    },
    menuItems: "menu_items",
    name: "name",
    resySelect: "resy_select",
    survey: "survey",
    taxIncluded: "tax_included",
    venueSlug: "venue_url_slug",
  },
};
